# Generated by Django 4.1.1 on 2024-04-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
